### ISSUE TITLE
Offer, not sure if you'll see this

### ISSUE THREAD

**Issue by puzzlementing** [IceHacks/BlogWriter#1]
Hi, I don't know how else to message you so here I am haha

Would you be interested in $100 paypal for a custom extension fix?

All I'm looking for are these simple features/changes:
- Turn auto-enemy detection in the smart switching into a toggle-able function
- Quick update to fix the current green 

You can add me on discord for quicker replies since I might not see this: boogie#1142

Thank you!

**Comment by IceHacks** [comment]
rip, never saw this lol
